<?php

namespace Database\Seeders;

class ProductSeederC extends ProductSeederPart
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Cedar Wool Coat',
                'category' => 'Men',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-CED-017',
                'price' => 189.90,
                'old_price' => 219.90,
                'short_description' => 'Warm wool coat with a sophisticated tailored silhouette.',
                'description' => 'A refined outer layer designed for cooler days and premium styling.',
                'sizes' => ['M', 'L', 'XL', '2XL'],
                'colors' => ['Charcoal', 'Navy', 'Black'],
                'tags' => ['men', 'clothing', 'fashion'],
                'material' => 'Wool Blend',
                'origin' => 'European Collection',
                'fit' => 'Tailored Fit',
                'availability' => 'In Stock',
                'stock' => 14,
                'rating' => 4.8,
                'review_count' => 17,
                'badge' => 'Premium',
                'is_featured' => true,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Celeste Handbag',
                'category' => 'Bags',
                'brand' => 'Dior',
                'sku' => 'ZNZ-CEL-018',
                'price' => 199.90,
                'old_price' => 229.90,
                'short_description' => 'Elegant structured handbag with premium detailing.',
                'description' => 'A sophisticated handbag designed for refined everyday and occasion styling.',
                'sizes' => [],
                'colors' => ['Black', 'Cream'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 13,
                'rating' => 4.9,
                'review_count' => 32,
                'badge' => 'Featured',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Celine Pleated Skirt',
                'category' => 'Women',
                'brand' => 'Chanel',
                'sku' => 'ZNZ-CEL-019',
                'price' => 99.90,
                'old_price' => 119.90,
                'short_description' => 'Elegant pleated skirt with a fluid contemporary shape.',
                'description' => 'A versatile skirt designed for polished casual and occasion outfits.',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Black', 'Cream', 'Rose'],
                'tags' => ['women', 'fashion', 'clothing'],
                'material' => 'Premium Fabric',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 22,
                'rating' => 4.7,
                'review_count' => 15,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Crown Running Shoes',
                'category' => 'Shoes',
                'brand' => 'Prada',
                'sku' => 'ZNZ-CRO-020',
                'price' => 109.90,
                'old_price' => 129.90,
                'short_description' => 'Lightweight running shoes with a clean modern profile.',
                'description' => 'Comfort-focused footwear designed for active everyday movement.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Black', 'Grey'],
                'tags' => ['shoes', 'fashion'],
                'material' => 'Mesh Textile',
                'origin' => 'European Collection',
                'fit' => 'Comfort Fit',
                'availability' => 'In Stock',
                'stock' => 31,
                'rating' => 4.6,
                'review_count' => 14,
                'badge' => 'New',
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
            [
                'name' => 'Cobalt Leather Wallet',
                'category' => 'Accessories',
                'brand' => 'Louis Vuitton',
                'sku' => 'ZNZ-COB-021',
                'price' => 64.90,
                'old_price' => 74.90,
                'short_description' => 'Compact leather wallet with practical card storage.',
                'description' => 'A premium wallet designed for organized everyday carry.',
                'sizes' => [],
                'colors' => ['Black', 'Brown'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Leather',
                'origin' => 'European Collection',
                'fit' => 'Compact',
                'availability' => 'In Stock',
                'stock' => 47,
                'rating' => 4.7,
                'review_count' => 23,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Canyon Denim Jacket',
                'category' => 'Clothing',
                'brand' => 'Gucci',
                'sku' => 'ZNZ-CAN-022',
                'price' => 109.90,
                'old_price' => 129.90,
                'short_description' => 'Classic denim jacket updated with a modern premium finish.',
                'description' => 'A versatile denim layer suitable for casual everyday outfits.',
                'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
                'colors' => ['Blue', 'Black'],
                'tags' => ['clothing', 'fashion'],
                'material' => 'Denim',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 26,
                'rating' => 4.6,
                'review_count' => 12,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Cloud Kids Sweatshirt',
                'category' => 'Kids',
                'brand' => 'Dior',
                'sku' => 'ZNZ-CLO-023',
                'price' => 44.90,
                'old_price' => 54.90,
                'short_description' => 'Soft sweatshirt designed for comfortable everyday wear.',
                'description' => 'A cozy casual sweatshirt made for active children.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Grey', 'Blue', 'Cream'],
                'tags' => ['kids', 'clothing', 'fashion'],
                'material' => 'Cotton Blend',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 33,
                'rating' => 4.5,
                'review_count' => 10,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Crest Travel Backpack',
                'category' => 'Bags',
                'brand' => 'Armani',
                'sku' => 'ZNZ-CRE-024',
                'price' => 129.90,
                'old_price' => 149.90,
                'short_description' => 'Functional travel backpack with a refined urban design.',
                'description' => 'A spacious backpack designed for commuting, travel and everyday use.',
                'sizes' => [],
                'colors' => ['Black', 'Navy'],
                'tags' => ['bags', 'product', 'fashion'],
                'material' => 'Technical Fabric',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 19,
                'rating' => 4.8,
                'review_count' => 18,
                'badge' => 'Popular',
                'is_featured' => true,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
        ];

        foreach ($products as $product) {
            $this->createProduct($product);
        }
    }
}
