<?php

namespace Database\Seeders;

class ProductSeederE extends ProductSeederPart
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Everest Knit Polo',
                'category' => 'Men',
                'brand' => 'Armani',
                'sku' => 'ZNZ-EVE-033',
                'price' => 74.90,
                'old_price' => 89.90,
                'short_description' => 'Premium knit polo with a refined relaxed silhouette.',
                'description' => 'A comfortable knit polo suitable for smart casual occasions.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Navy', 'Cream', 'Black'],
                'tags' => ['men', 'clothing', 'fashion'],
                'material' => 'Cotton Knit',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 30,
                'rating' => 4.7,
                'review_count' => 15,
                'badge' => 'Popular',
                'is_featured' => true,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Elara Mini Bag',
                'category' => 'Bags',
                'brand' => 'Prada',
                'sku' => 'ZNZ-ELA-034',
                'price' => 139.90,
                'old_price' => 159.90,
                'short_description' => 'Compact mini bag with modern premium styling.',
                'description' => 'A fashionable compact bag designed for lightweight everyday carry.',
                'sizes' => [],
                'colors' => ['Black', 'Rose'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Compact',
                'availability' => 'In Stock',
                'stock' => 17,
                'rating' => 4.8,
                'review_count' => 24,
                'badge' => 'New',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Eden Wrap Dress',
                'category' => 'Women',
                'brand' => 'Dior',
                'sku' => 'ZNZ-EDN-035',
                'price' => 119.90,
                'old_price' => 139.90,
                'short_description' => 'Elegant wrap dress with a flattering contemporary shape.',
                'description' => 'A sophisticated wrap dress suitable for occasions and refined daily styling.',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Rose', 'Navy', 'Black'],
                'tags' => ['women', 'fashion', 'clothing'],
                'material' => 'Premium Fabric',
                'origin' => 'European Collection',
                'fit' => 'Wrap Fit',
                'availability' => 'In Stock',
                'stock' => 19,
                'rating' => 4.8,
                'review_count' => 20,
                'badge' => 'Featured',
                'is_featured' => true,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Echo Court Shoes',
                'category' => 'Shoes',
                'brand' => 'Chanel',
                'sku' => 'ZNZ-ECH-036',
                'price' => 129.90,
                'old_price' => 149.90,
                'short_description' => 'Elegant court shoes with a refined silhouette.',
                'description' => 'Classic footwear designed for formal and occasion styling.',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Black', 'Cream'],
                'tags' => ['shoes', 'fashion', 'women'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 14,
                'rating' => 4.8,
                'review_count' => 18,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
            [
                'name' => 'Eclipse Leather Bracelet',
                'category' => 'Accessories',
                'brand' => 'Hermès',
                'sku' => 'ZNZ-ECL-037',
                'price' => 54.90,
                'old_price' => 64.90,
                'short_description' => 'Minimal leather bracelet with premium detailing.',
                'description' => 'A refined accessory designed to add subtle character to everyday outfits.',
                'sizes' => [],
                'colors' => ['Black', 'Brown'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Leather',
                'origin' => 'European Collection',
                'fit' => 'Adjustable',
                'availability' => 'In Stock',
                'stock' => 42,
                'rating' => 4.5,
                'review_count' => 10,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Essential Crewneck',
                'category' => 'Clothing',
                'brand' => 'Gucci',
                'sku' => 'ZNZ-ESS-038',
                'price' => 64.90,
                'old_price' => 74.90,
                'short_description' => 'Clean crewneck sweatshirt for everyday layering.',
                'description' => 'A comfortable wardrobe essential with a premium soft finish.',
                'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
                'colors' => ['Grey', 'Black', 'Cream'],
                'tags' => ['clothing', 'fashion'],
                'material' => 'Cotton Blend',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 34,
                'rating' => 4.6,
                'review_count' => 16,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Elm Kids Jacket',
                'category' => 'Kids',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-ELM-039',
                'price' => 69.90,
                'old_price' => 79.90,
                'short_description' => 'Lightweight jacket designed for active children.',
                'description' => 'A practical kids jacket suitable for outdoor and everyday use.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Navy', 'Blue', 'Black'],
                'tags' => ['kids', 'clothing'],
                'material' => 'Technical Fabric',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 16,
                'rating' => 4.6,
                'review_count' => 7,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Evergreen Travel Tote',
                'category' => 'Bags',
                'brand' => 'Louis Vuitton',
                'sku' => 'ZNZ-EVG-040',
                'price' => 189.90,
                'old_price' => 219.90,
                'short_description' => 'Large premium tote designed for travel and daily use.',
                'description' => 'A spacious tote balancing travel practicality with sophisticated styling.',
                'sizes' => [],
                'colors' => ['Brown', 'Black'],
                'tags' => ['bags', 'product', 'fashion'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 12,
                'rating' => 4.9,
                'review_count' => 30,
                'badge' => 'Premium',
                'is_featured' => true,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
        ];
        foreach ($products as $product) {
            $this->createProduct($product);
        }
    }
}
