<?php

namespace Database\Seeders;

class ProductSeederA extends ProductSeederPart
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Alpine Cotton Overshirt',
                'category' => 'Men',
                'brand' => 'Armani',
                'sku' => 'ZNZ-ALP-001',
                'price' => 79.90,
                'old_price' => 94.90,
                'short_description' => 'Premium cotton overshirt with a clean everyday silhouette.',
                'description' => 'A versatile cotton overshirt designed for comfortable everyday styling.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Black', 'Navy', 'Beige'],
                'tags' => ['fashion', 'clothing', 'men'],
                'material' => 'Premium Cotton',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 32,
                'rating' => 4.7,
                'review_count' => 18,
                'badge' => 'New',
                'is_featured' => true,
                'image' => $this->image(1),
                'images' => $this->images(1),
            ],
            [
                'name' => 'Avenue Leather Handbag',
                'category' => 'Bags',
                'brand' => 'Gucci',
                'sku' => 'ZNZ-AVE-002',
                'price' => 189.90,
                'old_price' => 219.90,
                'short_description' => 'Structured leather handbag for refined everyday styling.',
                'description' => 'A premium handbag combining practical storage with sophisticated design.',
                'sizes' => [],
                'colors' => ['Black', 'Tan'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 16,
                'rating' => 4.9,
                'review_count' => 34,
                'badge' => 'Popular',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2),
            ],
            [
                'name' => 'Aster Women Blazer',
                'category' => 'Women',
                'brand' => 'Chanel',
                'sku' => 'ZNZ-AST-003',
                'price' => 149.00,
                'old_price' => 179.00,
                'short_description' => 'Elegant tailored blazer with a contemporary finish.',
                'description' => 'A polished blazer designed for sophisticated office and occasion styling.',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Cream', 'Black', 'Grey'],
                'tags' => ['fashion', 'clothing', 'women'],
                'material' => 'Premium Fabric',
                'origin' => 'European Collection',
                'fit' => 'Tailored Fit',
                'availability' => 'In Stock',
                'stock' => 24,
                'rating' => 4.8,
                'review_count' => 22,
                'badge' => 'Featured',
                'is_featured' => true,
                'image' => $this->image(3),
                'images' => $this->images(3),
            ],
            [
                'name' => 'Aspen Casual Sneakers',
                'category' => 'Shoes',
                'brand' => 'Prada',
                'sku' => 'ZNZ-ASP-004',
                'price' => 119.90,
                'old_price' => 139.90,
                'short_description' => 'Modern casual sneakers designed for everyday comfort.',
                'description' => 'Lightweight sneakers offering a clean appearance and comfortable daily wear.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Black'],
                'tags' => ['shoes', 'fashion'],
                'material' => 'Textile',
                'origin' => 'European Collection',
                'fit' => 'Comfort Fit',
                'availability' => 'In Stock',
                'stock' => 41,
                'rating' => 4.6,
                'review_count' => 15,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4),
            ],
            [
                'name' => 'Aurora Silk Scarf',
                'category' => 'Accessories',
                'brand' => 'Dior',
                'sku' => 'ZNZ-AUR-005',
                'price' => 69.90,
                'old_price' => 84.90,
                'short_description' => 'Soft premium scarf with an elegant printed finish.',
                'description' => 'A lightweight accessory created to complement modern premium outfits.',
                'sizes' => [],
                'colors' => ['Rose', 'Cream', 'Blue'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Silk Blend',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 38,
                'rating' => 4.8,
                'review_count' => 19,
                'badge' => 'New',
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1),
            ],
            [
                'name' => 'Atlas Travel Jacket',
                'category' => 'Clothing',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-ATL-006',
                'price' => 169.90,
                'old_price' => 199.90,
                'short_description' => 'Lightweight travel jacket built for versatile layering.',
                'description' => 'A practical premium jacket suitable for travel and everyday urban wear.',
                'sizes' => ['M', 'L', 'XL', '2XL'],
                'colors' => ['Navy', 'Olive'],
                'tags' => ['clothing', 'fashion'],
                'material' => 'Technical Cotton',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'Limited Stock',
                'stock' => 11,
                'rating' => 4.7,
                'review_count' => 14,
                'badge' => 'Limited',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2),
            ],
            [
                'name' => 'Aspire Kids Hoodie',
                'category' => 'Kids',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-ASP-007',
                'price' => 49.90,
                'old_price' => 59.90,
                'short_description' => 'Comfortable everyday hoodie designed for kids.',
                'description' => 'A soft casual hoodie combining comfort and a clean modern appearance.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Blue', 'Grey', 'Black'],
                'tags' => ['kids', 'clothing', 'fashion'],
                'material' => 'Cotton Blend',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 27,
                'rating' => 4.5,
                'review_count' => 9,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3),
            ],
            [
                'name' => 'Almond Leather Belt',
                'category' => 'Accessories',
                'brand' => 'Louis Vuitton',
                'sku' => 'ZNZ-ALM-008',
                'price' => 59.90,
                'old_price' => 69.90,
                'short_description' => 'Classic leather belt with a refined premium buckle.',
                'description' => 'A timeless accessory designed to complete smart casual outfits.',
                'sizes' => [],
                'colors' => ['Black', 'Brown'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Leather',
                'origin' => 'European Collection',
                'fit' => 'Adjustable',
                'availability' => 'In Stock',
                'stock' => 45,
                'rating' => 4.6,
                'review_count' => 12,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4),
            ],
        ];
        foreach ($products as $product) {
            $this->createProduct($product);
        }
    }
}
