<?php

namespace Database\Seeders;

class ProductSeederF extends ProductSeederPart
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Forest Linen Blazer',
                'category' => 'Men',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-FOR-041',
                'price' => 139.90,
                'old_price' => 164.90,
                'short_description' => 'Lightweight linen blazer with a polished modern fit.',
                'description' => 'A breathable blazer designed for smart casual and warm-weather occasions.',
                'sizes' => ['M', 'L', 'XL', '2XL'],
                'colors' => ['Beige', 'Navy', 'Grey'],
                'tags' => ['men', 'clothing', 'fashion'],
                'material' => 'Linen Blend',
                'origin' => 'European Collection',
                'fit' => 'Tailored Fit',
                'availability' => 'In Stock',
                'stock' => 13,
                'rating' => 4.7,
                'review_count' => 12,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Fleur Evening Bag',
                'category' => 'Bags',
                'brand' => 'Chanel',
                'sku' => 'ZNZ-FLE-042',
                'price' => 149.90,
                'old_price' => 174.90,
                'short_description' => 'Elegant evening bag with a refined compact profile.',
                'description' => 'A sophisticated evening accessory for formal and special occasions.',
                'sizes' => [],
                'colors' => ['Black', 'Rose'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Compact',
                'availability' => 'In Stock',
                'stock' => 10,
                'rating' => 4.9,
                'review_count' => 26,
                'badge' => 'Featured',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Flora Pleated Blouse',
                'category' => 'Women',
                'brand' => 'Gucci',
                'sku' => 'ZNZ-FLO-043',
                'price' => 89.90,
                'old_price' => 104.90,
                'short_description' => 'Elegant pleated blouse with a soft flowing silhouette.',
                'description' => 'A feminine blouse designed for refined office and casual styling.',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Cream', 'Rose', 'Black'],
                'tags' => ['women', 'fashion', 'clothing'],
                'material' => 'Soft Premium Fabric',
                'origin' => 'European Collection',
                'fit' => 'Relaxed Fit',
                'availability' => 'In Stock',
                'stock' => 24,
                'rating' => 4.7,
                'review_count' => 17,
                'badge' => 'New',
                'is_featured' => true,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Flex Training Sneakers',
                'category' => 'Shoes',
                'brand' => 'Prada',
                'sku' => 'ZNZ-FLE-044',
                'price' => 114.90,
                'old_price' => 134.90,
                'short_description' => 'Comfortable training sneakers with a lightweight construction.',
                'description' => 'Sport-inspired footwear designed for active everyday use.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Black', 'Grey'],
                'tags' => ['shoes', 'fashion'],
                'material' => 'Mesh Textile',
                'origin' => 'European Collection',
                'fit' => 'Comfort Fit',
                'availability' => 'In Stock',
                'stock' => 29,
                'rating' => 4.6,
                'review_count' => 14,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
            [
                'name' => 'Fossil Leather Card Holder',
                'category' => 'Accessories',
                'brand' => 'Louis Vuitton',
                'sku' => 'ZNZ-FOS-045',
                'price' => 44.90,
                'old_price' => 54.90,
                'short_description' => 'Slim leather card holder with practical everyday storage.',
                'description' => 'A compact accessory designed for minimalist everyday carry.',
                'sizes' => [],
                'colors' => ['Black', 'Brown'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Leather',
                'origin' => 'European Collection',
                'fit' => 'Compact',
                'availability' => 'In Stock',
                'stock' => 50,
                'rating' => 4.6,
                'review_count' => 21,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Fjord Utility Vest',
                'category' => 'Clothing',
                'brand' => 'Armani',
                'sku' => 'ZNZ-FJO-046',
                'price' => 99.90,
                'old_price' => 119.90,
                'short_description' => 'Functional utility vest with a contemporary layered look.',
                'description' => 'A versatile vest designed for modern casual layering.',
                'sizes' => ['M', 'L', 'XL', '2XL'],
                'colors' => ['Olive', 'Black', 'Navy'],
                'tags' => ['clothing', 'fashion'],
                'material' => 'Technical Cotton',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 18,
                'rating' => 4.5,
                'review_count' => 9,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Forest Kids Hoodie',
                'category' => 'Kids',
                'brand' => 'Dior',
                'sku' => 'ZNZ-FOR-047',
                'price' => 39.90,
                'old_price' => 49.90,
                'short_description' => 'Soft everyday hoodie designed for comfortable kids wear.',
                'description' => 'A cozy casual hoodie suitable for school, play and everyday activities.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Green', 'Grey', 'Blue'],
                'tags' => ['kids', 'clothing', 'fashion'],
                'material' => 'Cotton Blend',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 35,
                'rating' => 4.5,
                'review_count' => 8,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Fusion Laptop Backpack',
                'category' => 'Lifestyle',
                'brand' => 'Hermès',
                'sku' => 'ZNZ-FUS-048',
                'price' => 139.90,
                'old_price' => 159.90,
                'short_description' => 'Premium laptop backpack designed for modern daily travel.',
                'description' => 'A practical lifestyle backpack offering organized storage for work and commuting.',
                'sizes' => [],
                'colors' => ['Black', 'Navy'],
                'tags' => ['product', 'bags', 'lifestyle'],
                'material' => 'Technical Fabric',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 20,
                'rating' => 4.8,
                'review_count' => 19,
                'badge' => 'Popular',
                'is_featured' => true,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
        ];
        foreach ($products as $product) {
            $this->createProduct($product);
        }
    }
}
