<?php

namespace Database\Seeders;

class ProductSeederD extends ProductSeederPart
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Dover Oxford Shirt',
                'category' => 'Men',
                'brand' => 'Prada',
                'sku' => 'ZNZ-DOV-025',
                'price' => 69.90,
                'old_price' => 84.90,
                'short_description' => 'Classic Oxford shirt with premium everyday construction.',
                'description' => 'A versatile Oxford shirt suitable for smart casual wardrobes.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Blue', 'Grey'],
                'tags' => ['men', 'clothing', 'fashion'],
                'material' => 'Oxford Cotton',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 37,
                'rating' => 4.7,
                'review_count' => 19,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Dahlia Tote Bag',
                'category' => 'Bags',
                'brand' => 'Louis Vuitton',
                'sku' => 'ZNZ-DAH-026',
                'price' => 169.90,
                'old_price' => 199.90,
                'short_description' => 'Spacious tote bag with elegant everyday styling.',
                'description' => 'A practical tote designed for customers who prefer generous storage and premium design.',
                'sizes' => [],
                'colors' => ['Brown', 'Black', 'Tan'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 15,
                'rating' => 4.8,
                'review_count' => 25,
                'badge' => 'Featured',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Dune Women Cardigan',
                'category' => 'Women',
                'brand' => 'Hermès',
                'sku' => 'ZNZ-DUN-027',
                'price' => 94.90,
                'old_price' => 109.90,
                'short_description' => 'Soft cardigan with an elegant lightweight construction.',
                'description' => 'A versatile cardigan designed for layering across seasons.',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Cream', 'Beige', 'Black'],
                'tags' => ['women', 'fashion', 'clothing'],
                'material' => 'Soft Knit',
                'origin' => 'European Collection',
                'fit' => 'Relaxed Fit',
                'availability' => 'In Stock',
                'stock' => 21,
                'rating' => 4.7,
                'review_count' => 16,
                'badge' => 'New',
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Drift Leather Sneakers',
                'category' => 'Shoes',
                'brand' => 'Gucci',
                'sku' => 'ZNZ-DRI-028',
                'price' => 124.90,
                'old_price' => 144.90,
                'short_description' => 'Minimal leather sneakers for modern casual wardrobes.',
                'description' => 'Clean-profile sneakers combining premium appearance with everyday comfort.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Black'],
                'tags' => ['shoes', 'fashion'],
                'material' => 'Leather',
                'origin' => 'European Collection',
                'fit' => 'Comfort Fit',
                'availability' => 'In Stock',
                'stock' => 28,
                'rating' => 4.7,
                'review_count' => 21,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
            [
                'name' => 'Dawn Fashion Sunglasses',
                'category' => 'Accessories',
                'brand' => 'Chanel',
                'sku' => 'ZNZ-DAW-029',
                'price' => 79.90,
                'old_price' => 94.90,
                'short_description' => 'Modern sunglasses with a sophisticated premium frame.',
                'description' => 'A statement accessory designed to complement contemporary outfits.',
                'sizes' => [],
                'colors' => ['Black', 'Brown'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Acetate',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 36,
                'rating' => 4.6,
                'review_count' => 13,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'District Cargo Pants',
                'category' => 'Clothing',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-DIS-030',
                'price' => 84.90,
                'old_price' => 99.90,
                'short_description' => 'Modern cargo pants with practical everyday pockets.',
                'description' => 'Comfortable cargo pants designed for contemporary casual wardrobes.',
                'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
                'colors' => ['Olive', 'Black', 'Beige'],
                'tags' => ['clothing', 'fashion'],
                'material' => 'Cotton Twill',
                'origin' => 'European Collection',
                'fit' => 'Relaxed Fit',
                'availability' => 'In Stock',
                'stock' => 25,
                'rating' => 4.6,
                'review_count' => 11,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Daisy Kids Dress',
                'category' => 'Kids',
                'brand' => 'Dior',
                'sku' => 'ZNZ-DAI-031',
                'price' => 54.90,
                'old_price' => 64.90,
                'short_description' => 'Charming kids dress with a soft comfortable finish.',
                'description' => 'A playful and comfortable dress designed for special days and casual outings.',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Rose', 'Cream', 'Blue'],
                'tags' => ['kids', 'clothing', 'fashion'],
                'material' => 'Cotton Blend',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 18,
                'rating' => 4.7,
                'review_count' => 9,
                'badge' => 'New',
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Delta Messenger Bag',
                'category' => 'Bags',
                'brand' => 'Armani',
                'sku' => 'ZNZ-DEL-032',
                'price' => 119.90,
                'old_price' => 139.90,
                'short_description' => 'Compact messenger bag for work and everyday commuting.',
                'description' => 'A practical messenger bag with a clean professional appearance.',
                'sizes' => [],
                'colors' => ['Black', 'Navy'],
                'tags' => ['bags', 'product', 'fashion'],
                'material' => 'Technical Fabric',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 23,
                'rating' => 4.7,
                'review_count' => 17,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
        ];
        foreach ($products as $product) {
            $this->createProduct($product);
        }
    }
}
