<?php

namespace Database\Seeders;

class ProductSeederB extends ProductSeederPart
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Bamboo Linen Shirt',
                'category' => 'Men',
                'brand' => 'Armani',
                'sku' => 'ZNZ-BAM-009',
                'price' => 72.90,
                'old_price' => 84.90,
                'short_description' => 'Breathable linen shirt with a relaxed premium finish.',
                'description' => 'A lightweight linen shirt designed for warm-weather comfort and effortless styling.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Beige', 'Blue'],
                'tags' => ['men', 'clothing', 'fashion'],
                'material' => 'Linen Blend',
                'origin' => 'European Collection',
                'fit' => 'Relaxed Fit',
                'availability' => 'In Stock',
                'stock' => 35,
                'rating' => 4.6,
                'review_count' => 13,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Belle Shoulder Bag',
                'category' => 'Bags',
                'brand' => 'Chanel',
                'sku' => 'ZNZ-BEL-010',
                'price' => 159.90,
                'old_price' => 189.90,
                'short_description' => 'Compact shoulder bag with elegant structured styling.',
                'description' => 'A refined shoulder bag suitable for day-to-evening styling.',
                'sizes' => [],
                'colors' => ['Black', 'Cream'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'In Stock',
                'stock' => 18,
                'rating' => 4.8,
                'review_count' => 27,
                'badge' => 'Popular',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Bloom Midi Dress',
                'category' => 'Women',
                'brand' => 'Dior',
                'sku' => 'ZNZ-BLO-011',
                'price' => 129.90,
                'old_price' => 154.90,
                'short_description' => 'Elegant midi dress with a graceful contemporary silhouette.',
                'description' => 'A versatile midi dress designed for occasions and refined everyday styling.',
                'sizes' => ['XS', 'S', 'M', 'L'],
                'colors' => ['Rose', 'Black', 'Navy'],
                'tags' => ['women', 'fashion', 'clothing'],
                'material' => 'Premium Fabric',
                'origin' => 'European Collection',
                'fit' => 'Contemporary Fit',
                'availability' => 'In Stock',
                'stock' => 20,
                'rating' => 4.8,
                'review_count' => 21,
                'badge' => 'New',
                'is_featured' => true,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Bristol Leather Loafers',
                'category' => 'Shoes',
                'brand' => 'Gucci',
                'sku' => 'ZNZ-BRI-012',
                'price' => 139.90,
                'old_price' => 164.90,
                'short_description' => 'Classic leather loafers with a polished finish.',
                'description' => 'Comfortable loafers designed for smart office and formal styling.',
                'sizes' => ['M', 'L', 'XL'],
                'colors' => ['Black', 'Brown'],
                'tags' => ['shoes', 'fashion', 'men'],
                'material' => 'Leather',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 17,
                'rating' => 4.7,
                'review_count' => 16,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
            [
                'name' => 'Breeze Cotton Cap',
                'category' => 'Accessories',
                'brand' => 'Prada',
                'sku' => 'ZNZ-BRE-013',
                'price' => 39.90,
                'old_price' => 49.90,
                'short_description' => 'Minimal cotton cap for casual everyday outfits.',
                'description' => 'A simple premium cap designed for casual styling.',
                'sizes' => [],
                'colors' => ['Black', 'White', 'Navy'],
                'tags' => ['accessories', 'fashion'],
                'material' => 'Cotton',
                'origin' => 'European Collection',
                'fit' => 'Adjustable',
                'availability' => 'In Stock',
                'stock' => 52,
                'rating' => 4.5,
                'review_count' => 11,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(1),
                'images' => $this->images(1)
            ],
            [
                'name' => 'Brooklyn Oversized Hoodie',
                'category' => 'Clothing',
                'brand' => 'Burberry',
                'sku' => 'ZNZ-BRO-014',
                'price' => 89.90,
                'old_price' => 109.90,
                'short_description' => 'Soft oversized hoodie with premium casual styling.',
                'description' => 'A comfortable oversized hoodie designed for relaxed modern wardrobes.',
                'sizes' => ['M', 'L', 'XL', '2XL', '3XL'],
                'colors' => ['Grey', 'Black', 'Cream'],
                'tags' => ['clothing', 'fashion'],
                'material' => 'Cotton Blend',
                'origin' => 'European Collection',
                'fit' => 'Oversized Fit',
                'availability' => 'In Stock',
                'stock' => 29,
                'rating' => 4.7,
                'review_count' => 20,
                'badge' => 'Featured',
                'is_featured' => true,
                'image' => $this->image(2),
                'images' => $this->images(2)
            ],
            [
                'name' => 'Brighton Kids T-Shirt',
                'category' => 'Kids',
                'brand' => 'Armani',
                'sku' => 'ZNZ-BRI-015',
                'price' => 29.90,
                'old_price' => 34.90,
                'short_description' => 'Soft everyday t-shirt for active kids.',
                'description' => 'A comfortable cotton t-shirt suitable for everyday activities.',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['White', 'Blue', 'Yellow'],
                'tags' => ['kids', 'clothing'],
                'material' => 'Cotton',
                'origin' => 'European Collection',
                'fit' => 'Regular Fit',
                'availability' => 'In Stock',
                'stock' => 40,
                'rating' => 4.4,
                'review_count' => 8,
                'badge' => null,
                'is_featured' => false,
                'image' => $this->image(3),
                'images' => $this->images(3)
            ],
            [
                'name' => 'Boulder Crossbody Bag',
                'category' => 'Bags',
                'brand' => 'Hermès',
                'sku' => 'ZNZ-BOU-016',
                'price' => 179.90,
                'old_price' => 209.90,
                'short_description' => 'Premium crossbody bag for practical everyday use.',
                'description' => 'A compact premium bag balancing practical storage and elegant styling.',
                'sizes' => [],
                'colors' => ['Tan', 'Black'],
                'tags' => ['bags', 'fashion', 'accessories'],
                'material' => 'Synthetic Leather',
                'origin' => 'European Collection',
                'fit' => 'Standard',
                'availability' => 'Limited Stock',
                'stock' => 8,
                'rating' => 4.9,
                'review_count' => 29,
                'badge' => 'Limited',
                'is_featured' => true,
                'image' => $this->image(4),
                'images' => $this->images(4)
            ],
        ];
        foreach ($products as $product) {
            $this->createProduct($product);
        }
    }
}
